Let
- $X$ be data
- $L$ be loading vectors of PCA
- $Pc$ be the principal components
- $n$ be the number of rows
- $D$ be the covariance matrix $Pc$. So $D = Pc \times Pc^{T} / n $

$$
X L = Pc \ \rightarrow \ L^{T}X^{T}XL = Pc^{T} Pc = D \times n
$$

Therefore

$$
X \times D \times n = X \times Pc^{T} Pc
$$

So 

$$
 X = \frac{X Pc^{T}}{n} \times (Pc D^{-1}) = CoV(X, Pc) \times \text{scores}
$$

Below confirms:

In [1]:
import numpy as np
from sklearn.datasets import load_iris

iris = load_iris()
X = iris.data
M = np.mean(X, axis=0)
X = X - M
X = np.matrix(X)

In [2]:
from sklearn.decomposition import PCA

pca = PCA()
S = np.matrix(pca.fit_transform(X))

In [3]:
D = np.cov(S.T)
D[np.abs(D) <= 0.00001] = 0
D = np.matrix(D)
D

matrix([[4.22484077, 0.        , 0.        , 0.        ],
        [0.        , 0.24224357, 0.        , 0.        ],
        [0.        , 0.        , 0.07852391, 0.        ],
        [0.        , 0.        , 0.        , 0.02368303]])

In [6]:
np.round(
    ((X)*S.T)*S*D.I/150 + np.matrix(M),
    1
)

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
iris.data[:20,:]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3]])